// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package gauge_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Execution Status
type ExecutionStatus int32

const (
	ExecutionStatus_NOTEXECUTED ExecutionStatus = 0
	ExecutionStatus_PASSED      ExecutionStatus = 1
	ExecutionStatus_FAILED      ExecutionStatus = 2
	ExecutionStatus_SKIPPED     ExecutionStatus = 3
)

var ExecutionStatus_name = map[int32]string{
	0: "NOTEXECUTED",
	1: "PASSED",
	2: "FAILED",
	3: "SKIPPED",
}
var ExecutionStatus_value = map[string]int32{
	"NOTEXECUTED": 0,
	"PASSED":      1,
	"FAILED":      2,
	"SKIPPED":     3,
}

func (x ExecutionStatus) String() string {
	return proto.EnumName(ExecutionStatus_name, int32(x))
}
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{0}
}

// / Enumerates various item types that the proto item can contain. Valid types are: Step, Comment, Concept, Scenario, TableDrivenScenario, Table, Tags
type ProtoItem_ItemType int32

const (
	ProtoItem_Step                ProtoItem_ItemType = 0
	ProtoItem_Comment             ProtoItem_ItemType = 1
	ProtoItem_Concept             ProtoItem_ItemType = 2
	ProtoItem_Scenario            ProtoItem_ItemType = 3
	ProtoItem_TableDrivenScenario ProtoItem_ItemType = 4
	ProtoItem_Table               ProtoItem_ItemType = 5
	ProtoItem_Tags                ProtoItem_ItemType = 6
)

var ProtoItem_ItemType_name = map[int32]string{
	0: "Step",
	1: "Comment",
	2: "Concept",
	3: "Scenario",
	4: "TableDrivenScenario",
	5: "Table",
	6: "Tags",
}
var ProtoItem_ItemType_value = map[string]int32{
	"Step":                0,
	"Comment":             1,
	"Concept":             2,
	"Scenario":            3,
	"TableDrivenScenario": 4,
	"Table":               5,
	"Tags":                6,
}

func (x ProtoItem_ItemType) String() string {
	return proto.EnumName(ProtoItem_ItemType_name, int32(x))
}
func (ProtoItem_ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{1, 0}
}

// / Enum representing the types of Fragment
type Fragment_FragmentType int32

const (
	Fragment_Text      Fragment_FragmentType = 0
	Fragment_Parameter Fragment_FragmentType = 1
)

var Fragment_FragmentType_name = map[int32]string{
	0: "Text",
	1: "Parameter",
}
var Fragment_FragmentType_value = map[string]int32{
	"Text":      0,
	"Parameter": 1,
}

func (x Fragment_FragmentType) String() string {
	return proto.EnumName(Fragment_FragmentType_name, int32(x))
}
func (Fragment_FragmentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{8, 0}
}

// / Enum representing types of Parameter.
type Parameter_ParameterType int32

const (
	Parameter_Static         Parameter_ParameterType = 0
	Parameter_Dynamic        Parameter_ParameterType = 1
	Parameter_Special_String Parameter_ParameterType = 2
	Parameter_Special_Table  Parameter_ParameterType = 3
	Parameter_Table          Parameter_ParameterType = 4
)

var Parameter_ParameterType_name = map[int32]string{
	0: "Static",
	1: "Dynamic",
	2: "Special_String",
	3: "Special_Table",
	4: "Table",
}
var Parameter_ParameterType_value = map[string]int32{
	"Static":         0,
	"Dynamic":        1,
	"Special_String": 2,
	"Special_Table":  3,
	"Table":          4,
}

func (x Parameter_ParameterType) String() string {
	return proto.EnumName(Parameter_ParameterType_name, int32(x))
}
func (Parameter_ParameterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{9, 0}
}

type ProtoExecutionResult_ErrorType int32

const (
	ProtoExecutionResult_ASSERTION    ProtoExecutionResult_ErrorType = 0
	ProtoExecutionResult_VERIFICATION ProtoExecutionResult_ErrorType = 1
)

var ProtoExecutionResult_ErrorType_name = map[int32]string{
	0: "ASSERTION",
	1: "VERIFICATION",
}
var ProtoExecutionResult_ErrorType_value = map[string]int32{
	"ASSERTION":    0,
	"VERIFICATION": 1,
}

func (x ProtoExecutionResult_ErrorType) String() string {
	return proto.EnumName(ProtoExecutionResult_ErrorType_name, int32(x))
}
func (ProtoExecutionResult_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{14, 0}
}

type Error_ErrorType int32

const (
	Error_PARSE_ERROR      Error_ErrorType = 0
	Error_VALIDATION_ERROR Error_ErrorType = 1
)

var Error_ErrorType_name = map[int32]string{
	0: "PARSE_ERROR",
	1: "VALIDATION_ERROR",
}
var Error_ErrorType_value = map[string]int32{
	"PARSE_ERROR":      0,
	"VALIDATION_ERROR": 1,
}

func (x Error_ErrorType) String() string {
	return proto.EnumName(Error_ErrorType_name, int32(x))
}
func (Error_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{18, 0}
}

// / A proto object representing a Specification
// / A specification can contain Scenarios or Steps, besides Comments
type ProtoSpec struct {
	// / Heading describing the Specification
	SpecHeading string `protobuf:"bytes,1,opt,name=specHeading" json:"specHeading,omitempty"`
	// / A collection of items that come under this step
	Items []*ProtoItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	// / Flag indicating if this is a Table Driven Specification. The table is defined in the context, this is different from using a table parameter.
	IsTableDriven bool `protobuf:"varint,3,opt,name=isTableDriven" json:"isTableDriven,omitempty"`
	// / Contains a 'before' hook failure message. This happens when the `before_spec` hook has an error.
	PreHookFailures []*ProtoHookFailure `protobuf:"bytes,4,rep,name=preHookFailures" json:"preHookFailures,omitempty"`
	// / Contains a 'before' hook failure message. This happens when the `after_hook` hook has an error.
	PostHookFailures []*ProtoHookFailure `protobuf:"bytes,5,rep,name=postHookFailures" json:"postHookFailures,omitempty"`
	// / Contains the filename for that holds this specification.
	FileName string `protobuf:"bytes,6,opt,name=fileName" json:"fileName,omitempty"`
	// / Contains a list of tags that are defined at the specification level. Scenario tags are not present here.
	Tags []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	// / Additional information at pre hook exec time to be available on reports
	PreHookMessages []string `protobuf:"bytes,8,rep,name=preHookMessages" json:"preHookMessages,omitempty"`
	// / Additional information at post hook exec time to be available on reports
	PostHookMessages []string `protobuf:"bytes,9,rep,name=postHookMessages" json:"postHookMessages,omitempty"`
	// / [DEPRECATED, use preHookMessages] Additional information at pre hook exec time to be available on reports
	PreHookMessage []string `protobuf:"bytes,10,rep,name=preHookMessage" json:"preHookMessage,omitempty"` // Deprecated: Do not use.
	// / [DEPRECATED, use postHookMessages] Additional information at post hook exec time to be available on reports
	PostHookMessage      []string `protobuf:"bytes,11,rep,name=postHookMessage" json:"postHookMessage,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoSpec) Reset()         { *m = ProtoSpec{} }
func (m *ProtoSpec) String() string { return proto.CompactTextString(m) }
func (*ProtoSpec) ProtoMessage()    {}
func (*ProtoSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{0}
}
func (m *ProtoSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSpec.Unmarshal(m, b)
}
func (m *ProtoSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSpec.Marshal(b, m, deterministic)
}
func (dst *ProtoSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSpec.Merge(dst, src)
}
func (m *ProtoSpec) XXX_Size() int {
	return xxx_messageInfo_ProtoSpec.Size(m)
}
func (m *ProtoSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSpec proto.InternalMessageInfo

func (m *ProtoSpec) GetSpecHeading() string {
	if m != nil {
		return m.SpecHeading
	}
	return ""
}

func (m *ProtoSpec) GetItems() []*ProtoItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ProtoSpec) GetIsTableDriven() bool {
	if m != nil {
		return m.IsTableDriven
	}
	return false
}

func (m *ProtoSpec) GetPreHookFailures() []*ProtoHookFailure {
	if m != nil {
		return m.PreHookFailures
	}
	return nil
}

func (m *ProtoSpec) GetPostHookFailures() []*ProtoHookFailure {
	if m != nil {
		return m.PostHookFailures
	}
	return nil
}

func (m *ProtoSpec) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ProtoSpec) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ProtoSpec) GetPreHookMessages() []string {
	if m != nil {
		return m.PreHookMessages
	}
	return nil
}

func (m *ProtoSpec) GetPostHookMessages() []string {
	if m != nil {
		return m.PostHookMessages
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoSpec) GetPreHookMessage() []string {
	if m != nil {
		return m.PreHookMessage
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoSpec) GetPostHookMessage() []string {
	if m != nil {
		return m.PostHookMessage
	}
	return nil
}

// / Container for all valid Items under a Specification.
type ProtoItem struct {
	// / Itemtype of the current ProtoItem
	ItemType ProtoItem_ItemType `protobuf:"varint,1,opt,name=itemType,enum=gauge.messages.ProtoItem_ItemType" json:"itemType,omitempty"`
	// / Holds the Step definition. Valid only if ItemType = Step
	Step *ProtoStep `protobuf:"bytes,2,opt,name=step" json:"step,omitempty"`
	// / Holds the Concept definition. Valid only if ItemType = Concept
	Concept *ProtoConcept `protobuf:"bytes,3,opt,name=concept" json:"concept,omitempty"`
	// / Holds the Scenario definition. Valid only if ItemType = Scenario
	Scenario *ProtoScenario `protobuf:"bytes,4,opt,name=scenario" json:"scenario,omitempty"`
	// / Holds the TableDrivenScenario definition. Valid only if ItemType = TableDrivenScenario
	TableDrivenScenario *ProtoTableDrivenScenario `protobuf:"bytes,5,opt,name=tableDrivenScenario" json:"tableDrivenScenario,omitempty"`
	// / Holds the Comment definition. Valid only if ItemType = Comment
	Comment *ProtoComment `protobuf:"bytes,6,opt,name=comment" json:"comment,omitempty"`
	// / Holds the Table definition. Valid only if ItemType = Table
	Table *ProtoTable `protobuf:"bytes,7,opt,name=table" json:"table,omitempty"`
	// / Holds the Tags definition. Valid only if ItemType = Tags
	Tags                 *ProtoTags `protobuf:"bytes,8,opt,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoItem) Reset()         { *m = ProtoItem{} }
func (m *ProtoItem) String() string { return proto.CompactTextString(m) }
func (*ProtoItem) ProtoMessage()    {}
func (*ProtoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{1}
}
func (m *ProtoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoItem.Unmarshal(m, b)
}
func (m *ProtoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoItem.Marshal(b, m, deterministic)
}
func (dst *ProtoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoItem.Merge(dst, src)
}
func (m *ProtoItem) XXX_Size() int {
	return xxx_messageInfo_ProtoItem.Size(m)
}
func (m *ProtoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoItem proto.InternalMessageInfo

func (m *ProtoItem) GetItemType() ProtoItem_ItemType {
	if m != nil {
		return m.ItemType
	}
	return ProtoItem_Step
}

func (m *ProtoItem) GetStep() *ProtoStep {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ProtoItem) GetConcept() *ProtoConcept {
	if m != nil {
		return m.Concept
	}
	return nil
}

func (m *ProtoItem) GetScenario() *ProtoScenario {
	if m != nil {
		return m.Scenario
	}
	return nil
}

func (m *ProtoItem) GetTableDrivenScenario() *ProtoTableDrivenScenario {
	if m != nil {
		return m.TableDrivenScenario
	}
	return nil
}

func (m *ProtoItem) GetComment() *ProtoComment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ProtoItem) GetTable() *ProtoTable {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *ProtoItem) GetTags() *ProtoTags {
	if m != nil {
		return m.Tags
	}
	return nil
}

// / A proto object representing a Scenario
type ProtoScenario struct {
	// / Heading of the given Scenario
	ScenarioHeading string `protobuf:"bytes,1,opt,name=scenarioHeading" json:"scenarioHeading,omitempty"`
	// / Flag to indicate if the Scenario execution failed
	Failed bool `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"` // Deprecated: Do not use.
	// / Collection of Context steps. The Context steps are executed before every run.
	Contexts []*ProtoItem `protobuf:"bytes,3,rep,name=contexts" json:"contexts,omitempty"`
	// / Collection of Items under a scenario. These could be Steps, Comments, Tags, TableDrivenScenarios or Tables
	ScenarioItems []*ProtoItem `protobuf:"bytes,4,rep,name=scenarioItems" json:"scenarioItems,omitempty"`
	// / Contains a 'before' hook failure message. This happens when the `before_scenario` hook has an error.
	PreHookFailure *ProtoHookFailure `protobuf:"bytes,5,opt,name=preHookFailure" json:"preHookFailure,omitempty"`
	// / Contains a 'after' hook failure message. This happens when the `after_scenario` hook has an error.
	PostHookFailure *ProtoHookFailure `protobuf:"bytes,6,opt,name=postHookFailure" json:"postHookFailure,omitempty"`
	// / Contains a list of tags that are defined at the specification level. Scenario tags are not present here.
	Tags []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	// / Holds the time taken for executing this scenario.
	ExecutionTime int64 `protobuf:"varint,8,opt,name=executionTime" json:"executionTime,omitempty"`
	// / Flag to indicate if the Scenario execution is skipped
	Skipped bool `protobuf:"varint,9,opt,name=skipped" json:"skipped,omitempty"` // Deprecated: Do not use.
	// / Holds the error messages for skipping scenario from execution
	SkipErrors []string `protobuf:"bytes,10,rep,name=skipErrors" json:"skipErrors,omitempty"`
	// / Holds the unique Identifier of a scenario.
	ID string `protobuf:"bytes,11,opt,name=ID" json:"ID,omitempty"`
	// / Collection of Teardown steps. The Teardown steps are executed after every run.
	TearDownSteps []*ProtoItem `protobuf:"bytes,12,rep,name=tearDownSteps" json:"tearDownSteps,omitempty"`
	// / Span(start, end) of scenario
	Span *Span `protobuf:"bytes,13,opt,name=span" json:"span,omitempty"`
	// / Execution status for the scenario
	ExecutionStatus ExecutionStatus `protobuf:"varint,14,opt,name=executionStatus,enum=gauge.messages.ExecutionStatus" json:"executionStatus,omitempty"`
	// / Additional information at pre hook exec time to be available on reports
	PreHookMessages []string `protobuf:"bytes,15,rep,name=preHookMessages" json:"preHookMessages,omitempty"`
	// / Additional information at post hook exec time to be available on reports
	PostHookMessages []string `protobuf:"bytes,16,rep,name=postHookMessages" json:"postHookMessages,omitempty"`
	// / [DEPRECATED, use preHookMessages] Additional information at pre hook exec time to be available on reports
	PreHookMessage []string `protobuf:"bytes,17,rep,name=preHookMessage" json:"preHookMessage,omitempty"` // Deprecated: Do not use.
	// / [DEPRECATED, use postHookMessages] Additional information at post hook exec time to be available on reports
	PostHookMessage      []string `protobuf:"bytes,18,rep,name=postHookMessage" json:"postHookMessage,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoScenario) Reset()         { *m = ProtoScenario{} }
func (m *ProtoScenario) String() string { return proto.CompactTextString(m) }
func (*ProtoScenario) ProtoMessage()    {}
func (*ProtoScenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{2}
}
func (m *ProtoScenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoScenario.Unmarshal(m, b)
}
func (m *ProtoScenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoScenario.Marshal(b, m, deterministic)
}
func (dst *ProtoScenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoScenario.Merge(dst, src)
}
func (m *ProtoScenario) XXX_Size() int {
	return xxx_messageInfo_ProtoScenario.Size(m)
}
func (m *ProtoScenario) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoScenario.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoScenario proto.InternalMessageInfo

func (m *ProtoScenario) GetScenarioHeading() string {
	if m != nil {
		return m.ScenarioHeading
	}
	return ""
}

// Deprecated: Do not use.
func (m *ProtoScenario) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *ProtoScenario) GetContexts() []*ProtoItem {
	if m != nil {
		return m.Contexts
	}
	return nil
}

func (m *ProtoScenario) GetScenarioItems() []*ProtoItem {
	if m != nil {
		return m.ScenarioItems
	}
	return nil
}

func (m *ProtoScenario) GetPreHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PreHookFailure
	}
	return nil
}

func (m *ProtoScenario) GetPostHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PostHookFailure
	}
	return nil
}

func (m *ProtoScenario) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ProtoScenario) GetExecutionTime() int64 {
	if m != nil {
		return m.ExecutionTime
	}
	return 0
}

// Deprecated: Do not use.
func (m *ProtoScenario) GetSkipped() bool {
	if m != nil {
		return m.Skipped
	}
	return false
}

func (m *ProtoScenario) GetSkipErrors() []string {
	if m != nil {
		return m.SkipErrors
	}
	return nil
}

func (m *ProtoScenario) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProtoScenario) GetTearDownSteps() []*ProtoItem {
	if m != nil {
		return m.TearDownSteps
	}
	return nil
}

func (m *ProtoScenario) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *ProtoScenario) GetExecutionStatus() ExecutionStatus {
	if m != nil {
		return m.ExecutionStatus
	}
	return ExecutionStatus_NOTEXECUTED
}

func (m *ProtoScenario) GetPreHookMessages() []string {
	if m != nil {
		return m.PreHookMessages
	}
	return nil
}

func (m *ProtoScenario) GetPostHookMessages() []string {
	if m != nil {
		return m.PostHookMessages
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoScenario) GetPreHookMessage() []string {
	if m != nil {
		return m.PreHookMessage
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoScenario) GetPostHookMessage() []string {
	if m != nil {
		return m.PostHookMessage
	}
	return nil
}

// / A proto object representing a Span of content
type Span struct {
	Start                int64    `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	StartChar            int64    `protobuf:"varint,3,opt,name=startChar" json:"startChar,omitempty"`
	EndChar              int64    `protobuf:"varint,4,opt,name=endChar" json:"endChar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{3}
}
func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (dst *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(dst, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Span) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Span) GetStartChar() int64 {
	if m != nil {
		return m.StartChar
	}
	return 0
}

func (m *Span) GetEndChar() int64 {
	if m != nil {
		return m.EndChar
	}
	return 0
}

// / A proto object representing a TableDrivenScenario
type ProtoTableDrivenScenario struct {
	// / Scenario under Table driven execution
	Scenario *ProtoScenario `protobuf:"bytes,1,opt,name=scenario" json:"scenario,omitempty"`
	// / Row Index of data table against which the current scenario is executed
	TableRowIndex        int32    `protobuf:"varint,2,opt,name=tableRowIndex" json:"tableRowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTableDrivenScenario) Reset()         { *m = ProtoTableDrivenScenario{} }
func (m *ProtoTableDrivenScenario) String() string { return proto.CompactTextString(m) }
func (*ProtoTableDrivenScenario) ProtoMessage()    {}
func (*ProtoTableDrivenScenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{4}
}
func (m *ProtoTableDrivenScenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTableDrivenScenario.Unmarshal(m, b)
}
func (m *ProtoTableDrivenScenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTableDrivenScenario.Marshal(b, m, deterministic)
}
func (dst *ProtoTableDrivenScenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTableDrivenScenario.Merge(dst, src)
}
func (m *ProtoTableDrivenScenario) XXX_Size() int {
	return xxx_messageInfo_ProtoTableDrivenScenario.Size(m)
}
func (m *ProtoTableDrivenScenario) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTableDrivenScenario.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTableDrivenScenario proto.InternalMessageInfo

func (m *ProtoTableDrivenScenario) GetScenario() *ProtoScenario {
	if m != nil {
		return m.Scenario
	}
	return nil
}

func (m *ProtoTableDrivenScenario) GetTableRowIndex() int32 {
	if m != nil {
		return m.TableRowIndex
	}
	return 0
}

// / A proto object representing a Step
type ProtoStep struct {
	// / Holds the raw text of the Step as defined in the spec file. This contains the actual parameter values.
	ActualText string `protobuf:"bytes,1,opt,name=actualText" json:"actualText,omitempty"`
	// / Contains the parsed text of the Step. This will have placeholders for the parameters.
	ParsedText string `protobuf:"bytes,2,opt,name=parsedText" json:"parsedText,omitempty"`
	// / Collection of a list of fragments for a Step. A fragment could be either text or parameter.
	Fragments []*Fragment `protobuf:"bytes,3,rep,name=fragments" json:"fragments,omitempty"`
	// / Holds the result from the execution.
	StepExecutionResult *ProtoStepExecutionResult `protobuf:"bytes,4,opt,name=stepExecutionResult" json:"stepExecutionResult,omitempty"`
	// / Additional information at pre hook exec time to be available on reports
	PreHookMessages []string `protobuf:"bytes,5,rep,name=preHookMessages" json:"preHookMessages,omitempty"`
	// / Additional information at post hook exec time to be available on reports
	PostHookMessages     []string `protobuf:"bytes,6,rep,name=postHookMessages" json:"postHookMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStep) Reset()         { *m = ProtoStep{} }
func (m *ProtoStep) String() string { return proto.CompactTextString(m) }
func (*ProtoStep) ProtoMessage()    {}
func (*ProtoStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{5}
}
func (m *ProtoStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStep.Unmarshal(m, b)
}
func (m *ProtoStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStep.Marshal(b, m, deterministic)
}
func (dst *ProtoStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStep.Merge(dst, src)
}
func (m *ProtoStep) XXX_Size() int {
	return xxx_messageInfo_ProtoStep.Size(m)
}
func (m *ProtoStep) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStep.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStep proto.InternalMessageInfo

func (m *ProtoStep) GetActualText() string {
	if m != nil {
		return m.ActualText
	}
	return ""
}

func (m *ProtoStep) GetParsedText() string {
	if m != nil {
		return m.ParsedText
	}
	return ""
}

func (m *ProtoStep) GetFragments() []*Fragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

func (m *ProtoStep) GetStepExecutionResult() *ProtoStepExecutionResult {
	if m != nil {
		return m.StepExecutionResult
	}
	return nil
}

func (m *ProtoStep) GetPreHookMessages() []string {
	if m != nil {
		return m.PreHookMessages
	}
	return nil
}

func (m *ProtoStep) GetPostHookMessages() []string {
	if m != nil {
		return m.PostHookMessages
	}
	return nil
}

// / Concept is a type of step, that can have multiple Steps.
// / But from a caller's perspective, it is still used as any other Step
// / A proto object representing a Concept
type ProtoConcept struct {
	// / Represents the Step value of a Concept.
	ConceptStep *ProtoStep `protobuf:"bytes,1,opt,name=conceptStep" json:"conceptStep,omitempty"`
	// / Collection of Steps in the given concepts.
	Steps []*ProtoItem `protobuf:"bytes,2,rep,name=steps" json:"steps,omitempty"`
	// / Holds the execution result.
	ConceptExecutionResult *ProtoStepExecutionResult `protobuf:"bytes,3,opt,name=conceptExecutionResult" json:"conceptExecutionResult,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *ProtoConcept) Reset()         { *m = ProtoConcept{} }
func (m *ProtoConcept) String() string { return proto.CompactTextString(m) }
func (*ProtoConcept) ProtoMessage()    {}
func (*ProtoConcept) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{6}
}
func (m *ProtoConcept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoConcept.Unmarshal(m, b)
}
func (m *ProtoConcept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoConcept.Marshal(b, m, deterministic)
}
func (dst *ProtoConcept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoConcept.Merge(dst, src)
}
func (m *ProtoConcept) XXX_Size() int {
	return xxx_messageInfo_ProtoConcept.Size(m)
}
func (m *ProtoConcept) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoConcept.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoConcept proto.InternalMessageInfo

func (m *ProtoConcept) GetConceptStep() *ProtoStep {
	if m != nil {
		return m.ConceptStep
	}
	return nil
}

func (m *ProtoConcept) GetSteps() []*ProtoItem {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *ProtoConcept) GetConceptExecutionResult() *ProtoStepExecutionResult {
	if m != nil {
		return m.ConceptExecutionResult
	}
	return nil
}

// / A proto object representing Tags
type ProtoTags struct {
	// / A collection of Tags
	Tags                 []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTags) Reset()         { *m = ProtoTags{} }
func (m *ProtoTags) String() string { return proto.CompactTextString(m) }
func (*ProtoTags) ProtoMessage()    {}
func (*ProtoTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{7}
}
func (m *ProtoTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTags.Unmarshal(m, b)
}
func (m *ProtoTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTags.Marshal(b, m, deterministic)
}
func (dst *ProtoTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTags.Merge(dst, src)
}
func (m *ProtoTags) XXX_Size() int {
	return xxx_messageInfo_ProtoTags.Size(m)
}
func (m *ProtoTags) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTags.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTags proto.InternalMessageInfo

func (m *ProtoTags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// / A proto object representing Fragment.
// / Fragments, put together make up A Step
type Fragment struct {
	// / Type of Fragment, valid values are Text, Parameter
	FragmentType Fragment_FragmentType `protobuf:"varint,1,opt,name=fragmentType,enum=gauge.messages.Fragment_FragmentType" json:"fragmentType,omitempty"`
	// / Text part of the Fragment, valid only if FragmentType=Text
	Text string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	// / Parameter part of the Fragment, valid only if FragmentType=Parameter
	Parameter            *Parameter `protobuf:"bytes,3,opt,name=parameter" json:"parameter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fragment) Reset()         { *m = Fragment{} }
func (m *Fragment) String() string { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()    {}
func (*Fragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{8}
}
func (m *Fragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fragment.Unmarshal(m, b)
}
func (m *Fragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fragment.Marshal(b, m, deterministic)
}
func (dst *Fragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fragment.Merge(dst, src)
}
func (m *Fragment) XXX_Size() int {
	return xxx_messageInfo_Fragment.Size(m)
}
func (m *Fragment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fragment.DiscardUnknown(m)
}

var xxx_messageInfo_Fragment proto.InternalMessageInfo

func (m *Fragment) GetFragmentType() Fragment_FragmentType {
	if m != nil {
		return m.FragmentType
	}
	return Fragment_Text
}

func (m *Fragment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Fragment) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

// / A proto object representing Fragment.
type Parameter struct {
	// / Type of the Parameter. Valid values: Static, Dynamic, Special_String, Special_Table, Table
	ParameterType Parameter_ParameterType `protobuf:"varint,1,opt,name=parameterType,enum=gauge.messages.Parameter_ParameterType" json:"parameterType,omitempty"`
	// / Holds the value of the parameter
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	// / Holds the name of the parameter, used as Key to lookup the value.
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// / Holds the table value, if parameterType=Table or Special_Table
	Table                *ProtoTable `protobuf:"bytes,4,opt,name=table" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{9}
}
func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (dst *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(dst, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetParameterType() Parameter_ParameterType {
	if m != nil {
		return m.ParameterType
	}
	return Parameter_Static
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetTable() *ProtoTable {
	if m != nil {
		return m.Table
	}
	return nil
}

// / A proto object representing Comment.
type ProtoComment struct {
	// / Text representing the Comment.
	Text                 string   `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoComment) Reset()         { *m = ProtoComment{} }
func (m *ProtoComment) String() string { return proto.CompactTextString(m) }
func (*ProtoComment) ProtoMessage()    {}
func (*ProtoComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{10}
}
func (m *ProtoComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoComment.Unmarshal(m, b)
}
func (m *ProtoComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoComment.Marshal(b, m, deterministic)
}
func (dst *ProtoComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoComment.Merge(dst, src)
}
func (m *ProtoComment) XXX_Size() int {
	return xxx_messageInfo_ProtoComment.Size(m)
}
func (m *ProtoComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoComment.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoComment proto.InternalMessageInfo

func (m *ProtoComment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// / A proto object representing Table.
type ProtoTable struct {
	// / Contains the Headers for the table
	Headers *ProtoTableRow `protobuf:"bytes,1,opt,name=headers" json:"headers,omitempty"`
	// / Contains the Rows for the table
	Rows                 []*ProtoTableRow `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProtoTable) Reset()         { *m = ProtoTable{} }
func (m *ProtoTable) String() string { return proto.CompactTextString(m) }
func (*ProtoTable) ProtoMessage()    {}
func (*ProtoTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{11}
}
func (m *ProtoTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTable.Unmarshal(m, b)
}
func (m *ProtoTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTable.Marshal(b, m, deterministic)
}
func (dst *ProtoTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTable.Merge(dst, src)
}
func (m *ProtoTable) XXX_Size() int {
	return xxx_messageInfo_ProtoTable.Size(m)
}
func (m *ProtoTable) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTable.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTable proto.InternalMessageInfo

func (m *ProtoTable) GetHeaders() *ProtoTableRow {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ProtoTable) GetRows() []*ProtoTableRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

// / A proto object representing Table.
type ProtoTableRow struct {
	// / Represents the cells of a given table
	Cells                []string `protobuf:"bytes,1,rep,name=cells" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTableRow) Reset()         { *m = ProtoTableRow{} }
func (m *ProtoTableRow) String() string { return proto.CompactTextString(m) }
func (*ProtoTableRow) ProtoMessage()    {}
func (*ProtoTableRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{12}
}
func (m *ProtoTableRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTableRow.Unmarshal(m, b)
}
func (m *ProtoTableRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTableRow.Marshal(b, m, deterministic)
}
func (dst *ProtoTableRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTableRow.Merge(dst, src)
}
func (m *ProtoTableRow) XXX_Size() int {
	return xxx_messageInfo_ProtoTableRow.Size(m)
}
func (m *ProtoTableRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTableRow.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTableRow proto.InternalMessageInfo

func (m *ProtoTableRow) GetCells() []string {
	if m != nil {
		return m.Cells
	}
	return nil
}

// / A proto object representing Step Execution result
type ProtoStepExecutionResult struct {
	// / The actual result of the execution
	ExecutionResult *ProtoExecutionResult `protobuf:"bytes,1,opt,name=executionResult" json:"executionResult,omitempty"`
	// / Contains a 'before' hook failure message. This happens when the `before_step` hook has an error.
	PreHookFailure *ProtoHookFailure `protobuf:"bytes,2,opt,name=preHookFailure" json:"preHookFailure,omitempty"`
	// / Contains a 'after' hook failure message. This happens when the `after_step` hook has an error.
	PostHookFailure      *ProtoHookFailure `protobuf:"bytes,3,opt,name=postHookFailure" json:"postHookFailure,omitempty"`
	Skipped              bool              `protobuf:"varint,4,opt,name=skipped" json:"skipped,omitempty"`
	SkippedReason        string            `protobuf:"bytes,5,opt,name=skippedReason" json:"skippedReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProtoStepExecutionResult) Reset()         { *m = ProtoStepExecutionResult{} }
func (m *ProtoStepExecutionResult) String() string { return proto.CompactTextString(m) }
func (*ProtoStepExecutionResult) ProtoMessage()    {}
func (*ProtoStepExecutionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{13}
}
func (m *ProtoStepExecutionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStepExecutionResult.Unmarshal(m, b)
}
func (m *ProtoStepExecutionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStepExecutionResult.Marshal(b, m, deterministic)
}
func (dst *ProtoStepExecutionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStepExecutionResult.Merge(dst, src)
}
func (m *ProtoStepExecutionResult) XXX_Size() int {
	return xxx_messageInfo_ProtoStepExecutionResult.Size(m)
}
func (m *ProtoStepExecutionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStepExecutionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStepExecutionResult proto.InternalMessageInfo

func (m *ProtoStepExecutionResult) GetExecutionResult() *ProtoExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

func (m *ProtoStepExecutionResult) GetPreHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PreHookFailure
	}
	return nil
}

func (m *ProtoStepExecutionResult) GetPostHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PostHookFailure
	}
	return nil
}

func (m *ProtoStepExecutionResult) GetSkipped() bool {
	if m != nil {
		return m.Skipped
	}
	return false
}

func (m *ProtoStepExecutionResult) GetSkippedReason() string {
	if m != nil {
		return m.SkippedReason
	}
	return ""
}

// / A proto object representing the result of an execution
type ProtoExecutionResult struct {
	// / Flag to indicate failure
	Failed bool `protobuf:"varint,1,opt,name=failed" json:"failed,omitempty"`
	// / Flag to indicate if the error is recoverable from.
	RecoverableError bool `protobuf:"varint,2,opt,name=recoverableError" json:"recoverableError,omitempty"`
	// / The actual error message.
	ErrorMessage string `protobuf:"bytes,3,opt,name=errorMessage" json:"errorMessage,omitempty"`
	// / Stacktrace of the error
	StackTrace string `protobuf:"bytes,4,opt,name=stackTrace" json:"stackTrace,omitempty"`
	// / Byte array containing screenshot taken at the time of failure.
	ScreenShot []byte `protobuf:"bytes,5,opt,name=screenShot,proto3" json:"screenShot,omitempty"`
	// / Holds the time taken for executing this scenario.
	ExecutionTime int64 `protobuf:"varint,6,opt,name=executionTime" json:"executionTime,omitempty"`
	// / Additional information at exec time to be available on reports
	Message []string `protobuf:"bytes,7,rep,name=message" json:"message,omitempty"`
	// / Type of the Error. Valid values: ASSERTION, VERIFICATION. Default: ASSERTION
	ErrorType            ProtoExecutionResult_ErrorType `protobuf:"varint,8,opt,name=errorType,enum=gauge.messages.ProtoExecutionResult_ErrorType" json:"errorType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProtoExecutionResult) Reset()         { *m = ProtoExecutionResult{} }
func (m *ProtoExecutionResult) String() string { return proto.CompactTextString(m) }
func (*ProtoExecutionResult) ProtoMessage()    {}
func (*ProtoExecutionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{14}
}
func (m *ProtoExecutionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoExecutionResult.Unmarshal(m, b)
}
func (m *ProtoExecutionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoExecutionResult.Marshal(b, m, deterministic)
}
func (dst *ProtoExecutionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoExecutionResult.Merge(dst, src)
}
func (m *ProtoExecutionResult) XXX_Size() int {
	return xxx_messageInfo_ProtoExecutionResult.Size(m)
}
func (m *ProtoExecutionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoExecutionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoExecutionResult proto.InternalMessageInfo

func (m *ProtoExecutionResult) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *ProtoExecutionResult) GetRecoverableError() bool {
	if m != nil {
		return m.RecoverableError
	}
	return false
}

func (m *ProtoExecutionResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ProtoExecutionResult) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ProtoExecutionResult) GetScreenShot() []byte {
	if m != nil {
		return m.ScreenShot
	}
	return nil
}

func (m *ProtoExecutionResult) GetExecutionTime() int64 {
	if m != nil {
		return m.ExecutionTime
	}
	return 0
}

func (m *ProtoExecutionResult) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ProtoExecutionResult) GetErrorType() ProtoExecutionResult_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return ProtoExecutionResult_ASSERTION
}

// / A proto object representing a pre-hook failure.
// / Used to hold failure information for before_suite, before_spec, before_scenario and before_spec hooks.
type ProtoHookFailure struct {
	// / Stacktrace from the failure
	StackTrace string `protobuf:"bytes,1,opt,name=stackTrace" json:"stackTrace,omitempty"`
	// / Error message from the failure
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
	// / Byte array holding the screenshot taken at the time of failure.
	ScreenShot []byte `protobuf:"bytes,3,opt,name=screenShot,proto3" json:"screenShot,omitempty"`
	// / Contains table row index corresponding to datatable rows
	TableRowIndex        int32    `protobuf:"varint,4,opt,name=tableRowIndex" json:"tableRowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoHookFailure) Reset()         { *m = ProtoHookFailure{} }
func (m *ProtoHookFailure) String() string { return proto.CompactTextString(m) }
func (*ProtoHookFailure) ProtoMessage()    {}
func (*ProtoHookFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{15}
}
func (m *ProtoHookFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoHookFailure.Unmarshal(m, b)
}
func (m *ProtoHookFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoHookFailure.Marshal(b, m, deterministic)
}
func (dst *ProtoHookFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoHookFailure.Merge(dst, src)
}
func (m *ProtoHookFailure) XXX_Size() int {
	return xxx_messageInfo_ProtoHookFailure.Size(m)
}
func (m *ProtoHookFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoHookFailure.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoHookFailure proto.InternalMessageInfo

func (m *ProtoHookFailure) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ProtoHookFailure) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ProtoHookFailure) GetScreenShot() []byte {
	if m != nil {
		return m.ScreenShot
	}
	return nil
}

func (m *ProtoHookFailure) GetTableRowIndex() int32 {
	if m != nil {
		return m.TableRowIndex
	}
	return 0
}

// / A proto object representing the result of entire Suite execution.
type ProtoSuiteResult struct {
	// / Contains the result from the execution
	SpecResults []*ProtoSpecResult `protobuf:"bytes,1,rep,name=specResults" json:"specResults,omitempty"`
	// / Contains a 'before' hook failure message. This happens when the `before_suite` hook has an error
	PreHookFailure *ProtoHookFailure `protobuf:"bytes,2,opt,name=preHookFailure" json:"preHookFailure,omitempty"`
	// / Contains a 'after' hook failure message. This happens when the `after_suite` hook has an error
	PostHookFailure *ProtoHookFailure `protobuf:"bytes,3,opt,name=postHookFailure" json:"postHookFailure,omitempty"`
	// / Flag to indicate failure
	Failed bool `protobuf:"varint,4,opt,name=failed" json:"failed,omitempty"`
	// / Holds the count of number of Specifications that failed.
	SpecsFailedCount int32 `protobuf:"varint,5,opt,name=specsFailedCount" json:"specsFailedCount,omitempty"`
	// / Holds the time taken for executing the whole suite.
	ExecutionTime int64 `protobuf:"varint,6,opt,name=executionTime" json:"executionTime,omitempty"`
	// / Holds a metric indicating the success rate of the execution.
	SuccessRate float32 `protobuf:"fixed32,7,opt,name=successRate" json:"successRate,omitempty"`
	// / The environment against which execution was done
	Environment string `protobuf:"bytes,8,opt,name=environment" json:"environment,omitempty"`
	// / Tag expression used for filtering specification
	Tags string `protobuf:"bytes,9,opt,name=tags" json:"tags,omitempty"`
	// / Project name
	ProjectName string `protobuf:"bytes,10,opt,name=projectName" json:"projectName,omitempty"`
	// / Timestamp of when execution started
	Timestamp         string `protobuf:"bytes,11,opt,name=timestamp" json:"timestamp,omitempty"`
	SpecsSkippedCount int32  `protobuf:"varint,12,opt,name=specsSkippedCount" json:"specsSkippedCount,omitempty"`
	// / Additional information at pre hook exec time to be available on reports
	PreHookMessages []string `protobuf:"bytes,13,rep,name=preHookMessages" json:"preHookMessages,omitempty"`
	// / Additional information at post hook exec time to be available on reports
	PostHookMessages []string `protobuf:"bytes,14,rep,name=postHookMessages" json:"postHookMessages,omitempty"`
	// / [DEPRECATED, use preHookMessages] Additional information at pre hook exec time to be available on reports
	PreHookMessage []string `protobuf:"bytes,15,rep,name=preHookMessage" json:"preHookMessage,omitempty"` // Deprecated: Do not use.
	// / [DEPRECATED, use postHookMessages] Additional information at post hook exec time to be available on reports
	PostHookMessage      []string `protobuf:"bytes,16,rep,name=postHookMessage" json:"postHookMessage,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoSuiteResult) Reset()         { *m = ProtoSuiteResult{} }
func (m *ProtoSuiteResult) String() string { return proto.CompactTextString(m) }
func (*ProtoSuiteResult) ProtoMessage()    {}
func (*ProtoSuiteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{16}
}
func (m *ProtoSuiteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSuiteResult.Unmarshal(m, b)
}
func (m *ProtoSuiteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSuiteResult.Marshal(b, m, deterministic)
}
func (dst *ProtoSuiteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSuiteResult.Merge(dst, src)
}
func (m *ProtoSuiteResult) XXX_Size() int {
	return xxx_messageInfo_ProtoSuiteResult.Size(m)
}
func (m *ProtoSuiteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSuiteResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSuiteResult proto.InternalMessageInfo

func (m *ProtoSuiteResult) GetSpecResults() []*ProtoSpecResult {
	if m != nil {
		return m.SpecResults
	}
	return nil
}

func (m *ProtoSuiteResult) GetPreHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PreHookFailure
	}
	return nil
}

func (m *ProtoSuiteResult) GetPostHookFailure() *ProtoHookFailure {
	if m != nil {
		return m.PostHookFailure
	}
	return nil
}

func (m *ProtoSuiteResult) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *ProtoSuiteResult) GetSpecsFailedCount() int32 {
	if m != nil {
		return m.SpecsFailedCount
	}
	return 0
}

func (m *ProtoSuiteResult) GetExecutionTime() int64 {
	if m != nil {
		return m.ExecutionTime
	}
	return 0
}

func (m *ProtoSuiteResult) GetSuccessRate() float32 {
	if m != nil {
		return m.SuccessRate
	}
	return 0
}

func (m *ProtoSuiteResult) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *ProtoSuiteResult) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *ProtoSuiteResult) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ProtoSuiteResult) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ProtoSuiteResult) GetSpecsSkippedCount() int32 {
	if m != nil {
		return m.SpecsSkippedCount
	}
	return 0
}

func (m *ProtoSuiteResult) GetPreHookMessages() []string {
	if m != nil {
		return m.PreHookMessages
	}
	return nil
}

func (m *ProtoSuiteResult) GetPostHookMessages() []string {
	if m != nil {
		return m.PostHookMessages
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoSuiteResult) GetPreHookMessage() []string {
	if m != nil {
		return m.PreHookMessage
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProtoSuiteResult) GetPostHookMessage() []string {
	if m != nil {
		return m.PostHookMessage
	}
	return nil
}

// / A proto object representing the result of Spec execution.
type ProtoSpecResult struct {
	// / Represents the corresponding Specification
	ProtoSpec *ProtoSpec `protobuf:"bytes,1,opt,name=protoSpec" json:"protoSpec,omitempty"`
	// / Holds the number of Scenarios executed
	ScenarioCount int32 `protobuf:"varint,2,opt,name=scenarioCount" json:"scenarioCount,omitempty"`
	// / Holds the number of Scenarios failed
	ScenarioFailedCount int32 `protobuf:"varint,3,opt,name=scenarioFailedCount" json:"scenarioFailedCount,omitempty"`
	// / Flag to indicate failure
	Failed bool `protobuf:"varint,4,opt,name=failed" json:"failed,omitempty"`
	// / Holds the row numbers, which caused the execution to fail.
	FailedDataTableRows []int32 `protobuf:"varint,5,rep,packed,name=failedDataTableRows" json:"failedDataTableRows,omitempty"`
	// / Holds the time taken for executing the spec.
	ExecutionTime int64 `protobuf:"varint,6,opt,name=executionTime" json:"executionTime,omitempty"`
	// / Flag to indicate if spec is skipped
	Skipped bool `protobuf:"varint,7,opt,name=skipped" json:"skipped,omitempty"`
	// / Holds the number of Scenarios skipped
	ScenarioSkippedCount int32 `protobuf:"varint,8,opt,name=scenarioSkippedCount" json:"scenarioSkippedCount,omitempty"`
	// / Holds the row numbers, for which the execution skipped.
	SkippedDataTableRows []int32 `protobuf:"varint,9,rep,packed,name=skippedDataTableRows" json:"skippedDataTableRows,omitempty"`
	// / Holds parse, validation and skipped errors.
	Errors               []*Error `protobuf:"bytes,10,rep,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoSpecResult) Reset()         { *m = ProtoSpecResult{} }
func (m *ProtoSpecResult) String() string { return proto.CompactTextString(m) }
func (*ProtoSpecResult) ProtoMessage()    {}
func (*ProtoSpecResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{17}
}
func (m *ProtoSpecResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSpecResult.Unmarshal(m, b)
}
func (m *ProtoSpecResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSpecResult.Marshal(b, m, deterministic)
}
func (dst *ProtoSpecResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSpecResult.Merge(dst, src)
}
func (m *ProtoSpecResult) XXX_Size() int {
	return xxx_messageInfo_ProtoSpecResult.Size(m)
}
func (m *ProtoSpecResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSpecResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSpecResult proto.InternalMessageInfo

func (m *ProtoSpecResult) GetProtoSpec() *ProtoSpec {
	if m != nil {
		return m.ProtoSpec
	}
	return nil
}

func (m *ProtoSpecResult) GetScenarioCount() int32 {
	if m != nil {
		return m.ScenarioCount
	}
	return 0
}

func (m *ProtoSpecResult) GetScenarioFailedCount() int32 {
	if m != nil {
		return m.ScenarioFailedCount
	}
	return 0
}

func (m *ProtoSpecResult) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *ProtoSpecResult) GetFailedDataTableRows() []int32 {
	if m != nil {
		return m.FailedDataTableRows
	}
	return nil
}

func (m *ProtoSpecResult) GetExecutionTime() int64 {
	if m != nil {
		return m.ExecutionTime
	}
	return 0
}

func (m *ProtoSpecResult) GetSkipped() bool {
	if m != nil {
		return m.Skipped
	}
	return false
}

func (m *ProtoSpecResult) GetScenarioSkippedCount() int32 {
	if m != nil {
		return m.ScenarioSkippedCount
	}
	return 0
}

func (m *ProtoSpecResult) GetSkippedDataTableRows() []int32 {
	if m != nil {
		return m.SkippedDataTableRows
	}
	return nil
}

func (m *ProtoSpecResult) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

// / A proto object representing an error in spec/Scenario.
type Error struct {
	// / Holds the type of error
	Type Error_ErrorType `protobuf:"varint,1,opt,name=type,enum=gauge.messages.Error_ErrorType" json:"type,omitempty"`
	// / Holds the filename.
	Filename string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	// / Holds the line number of the error in file.
	LineNumber int32 `protobuf:"varint,3,opt,name=lineNumber" json:"lineNumber,omitempty"`
	// / Holds the error message.
	Message              string   `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{18}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetType() Error_ErrorType {
	if m != nil {
		return m.Type
	}
	return Error_PARSE_ERROR
}

func (m *Error) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Error) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// / A proto object representing a Step value.
type ProtoStepValue struct {
	// / The actual string value describing he Step
	StepValue string `protobuf:"bytes,1,opt,name=stepValue" json:"stepValue,omitempty"`
	// / The parameterized string value describing he Step. The parameters are replaced with placeholders.
	ParameterizedStepValue string `protobuf:"bytes,2,opt,name=parameterizedStepValue" json:"parameterizedStepValue,omitempty"`
	// / A collection of strings representing the parameters.
	Parameters           []string `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStepValue) Reset()         { *m = ProtoStepValue{} }
func (m *ProtoStepValue) String() string { return proto.CompactTextString(m) }
func (*ProtoStepValue) ProtoMessage()    {}
func (*ProtoStepValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_23af6e88e6be132d, []int{19}
}
func (m *ProtoStepValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStepValue.Unmarshal(m, b)
}
func (m *ProtoStepValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStepValue.Marshal(b, m, deterministic)
}
func (dst *ProtoStepValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStepValue.Merge(dst, src)
}
func (m *ProtoStepValue) XXX_Size() int {
	return xxx_messageInfo_ProtoStepValue.Size(m)
}
func (m *ProtoStepValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStepValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStepValue proto.InternalMessageInfo

func (m *ProtoStepValue) GetStepValue() string {
	if m != nil {
		return m.StepValue
	}
	return ""
}

func (m *ProtoStepValue) GetParameterizedStepValue() string {
	if m != nil {
		return m.ParameterizedStepValue
	}
	return ""
}

func (m *ProtoStepValue) GetParameters() []string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoSpec)(nil), "gauge.messages.ProtoSpec")
	proto.RegisterType((*ProtoItem)(nil), "gauge.messages.ProtoItem")
	proto.RegisterType((*ProtoScenario)(nil), "gauge.messages.ProtoScenario")
	proto.RegisterType((*Span)(nil), "gauge.messages.Span")
	proto.RegisterType((*ProtoTableDrivenScenario)(nil), "gauge.messages.ProtoTableDrivenScenario")
	proto.RegisterType((*ProtoStep)(nil), "gauge.messages.ProtoStep")
	proto.RegisterType((*ProtoConcept)(nil), "gauge.messages.ProtoConcept")
	proto.RegisterType((*ProtoTags)(nil), "gauge.messages.ProtoTags")
	proto.RegisterType((*Fragment)(nil), "gauge.messages.Fragment")
	proto.RegisterType((*Parameter)(nil), "gauge.messages.Parameter")
	proto.RegisterType((*ProtoComment)(nil), "gauge.messages.ProtoComment")
	proto.RegisterType((*ProtoTable)(nil), "gauge.messages.ProtoTable")
	proto.RegisterType((*ProtoTableRow)(nil), "gauge.messages.ProtoTableRow")
	proto.RegisterType((*ProtoStepExecutionResult)(nil), "gauge.messages.ProtoStepExecutionResult")
	proto.RegisterType((*ProtoExecutionResult)(nil), "gauge.messages.ProtoExecutionResult")
	proto.RegisterType((*ProtoHookFailure)(nil), "gauge.messages.ProtoHookFailure")
	proto.RegisterType((*ProtoSuiteResult)(nil), "gauge.messages.ProtoSuiteResult")
	proto.RegisterType((*ProtoSpecResult)(nil), "gauge.messages.ProtoSpecResult")
	proto.RegisterType((*Error)(nil), "gauge.messages.Error")
	proto.RegisterType((*ProtoStepValue)(nil), "gauge.messages.ProtoStepValue")
	proto.RegisterEnum("gauge.messages.ExecutionStatus", ExecutionStatus_name, ExecutionStatus_value)
	proto.RegisterEnum("gauge.messages.ProtoItem_ItemType", ProtoItem_ItemType_name, ProtoItem_ItemType_value)
	proto.RegisterEnum("gauge.messages.Fragment_FragmentType", Fragment_FragmentType_name, Fragment_FragmentType_value)
	proto.RegisterEnum("gauge.messages.Parameter_ParameterType", Parameter_ParameterType_name, Parameter_ParameterType_value)
	proto.RegisterEnum("gauge.messages.ProtoExecutionResult_ErrorType", ProtoExecutionResult_ErrorType_name, ProtoExecutionResult_ErrorType_value)
	proto.RegisterEnum("gauge.messages.Error_ErrorType", Error_ErrorType_name, Error_ErrorType_value)
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_spec_23af6e88e6be132d) }

var fileDescriptor_spec_23af6e88e6be132d = []byte{
	// 1848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5b, 0x8f, 0x1b, 0x49,
	0x15, 0x9e, 0xbe, 0xf8, 0x76, 0x7c, 0x99, 0x4e, 0x65, 0x08, 0x4d, 0x14, 0x12, 0xab, 0x35, 0xab,
	0x1d, 0xa2, 0xec, 0x10, 0x66, 0x45, 0x56, 0x08, 0x09, 0x34, 0x3b, 0xf6, 0x6c, 0x0c, 0xd9, 0xc9,
	0xa8, 0x6c, 0x22, 0xb4, 0x2f, 0x4b, 0xa7, 0x5d, 0xf1, 0xf4, 0xc6, 0xee, 0x6e, 0x75, 0x97, 0x93,
	0x59, 0x78, 0xe7, 0x07, 0xf0, 0xcc, 0x2f, 0xe0, 0x9d, 0x77, 0x24, 0x24, 0x5e, 0x22, 0x21, 0xf1,
	0x07, 0xf8, 0x21, 0x3c, 0x20, 0x54, 0xa7, 0xaa, 0xaf, 0x6e, 0x67, 0x1c, 0xc4, 0x03, 0x6f, 0x55,
	0xe7, 0x52, 0x5d, 0xe7, 0xd4, 0xa9, 0xef, 0x7c, 0xd5, 0x00, 0x49, 0xc4, 0xbc, 0xe3, 0x28, 0x0e,
	0x79, 0x48, 0x06, 0x0b, 0x77, 0xbd, 0x60, 0xc7, 0x2b, 0x96, 0x24, 0xee, 0x82, 0x25, 0xce, 0xbf,
	0x0d, 0xe8, 0x5c, 0x0a, 0xcd, 0x34, 0x62, 0x1e, 0x19, 0x42, 0x57, 0xd8, 0x3e, 0x65, 0xee, 0xdc,
	0x0f, 0x16, 0xb6, 0x36, 0xd4, 0x8e, 0x3a, 0xb4, 0x28, 0x22, 0x3f, 0x84, 0x86, 0xcf, 0xd9, 0x2a,
	0xb1, 0xf5, 0xa1, 0x71, 0xd4, 0x3d, 0xf9, 0xde, 0x71, 0x79, 0xbd, 0x63, 0x5c, 0x6b, 0xc2, 0xd9,
	0x8a, 0x4a, 0x3b, 0x72, 0x08, 0x7d, 0x3f, 0x99, 0xb9, 0x2f, 0x97, 0x6c, 0x14, 0xfb, 0x6f, 0x58,
	0x60, 0x1b, 0x43, 0xed, 0xa8, 0x4d, 0xcb, 0x42, 0xf2, 0x0b, 0xd8, 0x8f, 0x62, 0xf6, 0x34, 0x0c,
	0x5f, 0x9f, 0xbb, 0xfe, 0x72, 0x1d, 0xb3, 0xc4, 0x36, 0xf1, 0x03, 0xc3, 0xda, 0x0f, 0x14, 0x0c,
	0x69, 0xd5, 0x91, 0x3c, 0x03, 0x2b, 0x0a, 0x13, 0x5e, 0x5a, 0xac, 0xb1, 0xe3, 0x62, 0x1b, 0x9e,
	0xe4, 0x2e, 0xb4, 0x5f, 0xf9, 0x4b, 0x76, 0xe1, 0xae, 0x98, 0xdd, 0xc4, 0x7c, 0x64, 0x73, 0x42,
	0xc0, 0xe4, 0xee, 0x22, 0xb1, 0x5b, 0x43, 0xe3, 0xa8, 0x43, 0x71, 0x4c, 0x8e, 0xb2, 0x48, 0xbe,
	0x54, 0x5f, 0xb1, 0xdb, 0xa8, 0xae, 0x8a, 0xc9, 0xc3, 0x7c, 0x9f, 0x99, 0x69, 0x07, 0x4d, 0x37,
	0xe4, 0xe4, 0x21, 0x0c, 0xca, 0xee, 0x36, 0x08, 0xcb, 0xcf, 0x75, 0x5b, 0xa3, 0x15, 0x0d, 0x79,
	0x04, 0xfb, 0x15, 0x7f, 0xbb, 0x9b, 0x19, 0x57, 0x55, 0xce, 0xdf, 0x4d, 0x55, 0x00, 0xe2, 0xd0,
	0xc8, 0xcf, 0xa0, 0x2d, 0x8e, 0x6d, 0xf6, 0x6d, 0xc4, 0xf0, 0xf4, 0x07, 0x27, 0xce, 0xd6, 0x13,
	0x3e, 0x9e, 0x28, 0x4b, 0x9a, 0xf9, 0x90, 0x4f, 0xc0, 0x4c, 0x38, 0x8b, 0x6c, 0x7d, 0xa8, 0x6d,
	0xad, 0x8e, 0x29, 0x67, 0x11, 0x45, 0x33, 0xf2, 0x04, 0x5a, 0x5e, 0x18, 0x78, 0x2c, 0xe2, 0x58,
	0x16, 0xdd, 0x93, 0x7b, 0xb5, 0x1e, 0x67, 0xd2, 0x86, 0xa6, 0xc6, 0xe4, 0x27, 0xd0, 0x4e, 0x3c,
	0x16, 0xb8, 0xb1, 0x1f, 0xda, 0x26, 0x3a, 0x7e, 0xbf, 0xfe, 0x53, 0xca, 0x88, 0x66, 0xe6, 0xe4,
	0x2b, 0xb8, 0xcd, 0xf3, 0xc2, 0x4b, 0x0d, 0xec, 0x06, 0xae, 0x72, 0x54, 0xbb, 0xca, 0x6c, 0xd3,
	0x9e, 0xd6, 0x2d, 0x22, 0xc3, 0x59, 0xad, 0x58, 0xc0, 0xb1, 0x54, 0xb6, 0x87, 0x83, 0x36, 0x34,
	0x35, 0x26, 0x8f, 0xa1, 0x81, 0xcb, 0xd9, 0x2d, 0xf4, 0xba, 0xbb, 0x7d, 0x17, 0x54, 0x1a, 0x8a,
	0x3c, 0x63, 0xe5, 0xb5, 0xdf, 0x93, 0xe7, 0x99, 0xbb, 0x48, 0x64, 0x51, 0x3a, 0xdf, 0x40, 0x3b,
	0x3d, 0x2c, 0xd2, 0x06, 0x53, 0x9c, 0x80, 0xb5, 0x47, 0xba, 0xd0, 0x52, 0x5b, 0xb1, 0x34, 0x39,
	0xc1, 0xec, 0x5a, 0x3a, 0xe9, 0x41, 0x3b, 0x0d, 0xca, 0x32, 0xc8, 0x77, 0xe1, 0x76, 0x4d, 0x0a,
	0x2c, 0x93, 0x74, 0xa0, 0x81, 0x0a, 0xab, 0x21, 0x56, 0x15, 0xdf, 0xb3, 0x9a, 0xce, 0x3f, 0x9a,
	0xd0, 0x2f, 0x25, 0x5f, 0x5c, 0x89, 0x34, 0xfd, 0x65, 0x64, 0xa9, 0x8a, 0xc9, 0x5d, 0x68, 0xbe,
	0x72, 0xfd, 0x25, 0x9b, 0x63, 0x01, 0xb5, 0xb1, 0x62, 0x95, 0x84, 0xfc, 0x18, 0xda, 0x5e, 0x18,
	0x70, 0x76, 0xcd, 0x13, 0xdb, 0xb8, 0x09, 0x7c, 0x32, 0x53, 0xf2, 0x73, 0xe8, 0xa7, 0x5f, 0x99,
	0x20, 0x70, 0x99, 0x37, 0xf9, 0x96, 0xed, 0xc9, 0xd3, 0xec, 0xea, 0x29, 0x4c, 0x50, 0xb5, 0x72,
	0x33, 0x98, 0x54, 0xfc, 0x10, 0xe4, 0xca, 0xf0, 0xa2, 0xca, 0x64, 0x17, 0x90, 0x2b, 0x3b, 0xd6,
	0x42, 0xcf, 0x21, 0xf4, 0xd9, 0x35, 0xf3, 0xd6, 0xdc, 0x0f, 0x83, 0x99, 0xbf, 0x62, 0x58, 0x1d,
	0x06, 0x2d, 0x0b, 0xc9, 0x3d, 0x68, 0x25, 0xaf, 0xfd, 0x28, 0x62, 0x73, 0xbb, 0x93, 0x25, 0x39,
	0x15, 0x91, 0xfb, 0x00, 0x62, 0x38, 0x8e, 0xe3, 0x30, 0x4e, 0x24, 0xc8, 0xd0, 0x82, 0x84, 0x0c,
	0x40, 0x9f, 0x8c, 0xec, 0x2e, 0x1e, 0x9f, 0x3e, 0x19, 0x89, 0xf4, 0x72, 0xe6, 0xc6, 0xa3, 0xf0,
	0x6d, 0x20, 0xaa, 0x2a, 0xb1, 0x7b, 0x37, 0xa6, 0xb7, 0x64, 0x4f, 0x8e, 0xc0, 0x4c, 0x22, 0x37,
	0xb0, 0xfb, 0x98, 0x89, 0x83, 0xaa, 0xdf, 0x34, 0x72, 0x03, 0x8a, 0x16, 0x64, 0x02, 0xfb, 0x59,
	0x24, 0x53, 0xee, 0xf2, 0x75, 0x62, 0x0f, 0x10, 0xa2, 0x1e, 0x54, 0x9d, 0xc6, 0x65, 0x33, 0x5a,
	0xf5, 0xab, 0x03, 0xe9, 0xfd, 0xdd, 0x41, 0xda, 0xda, 0x19, 0xa4, 0x6f, 0x7d, 0x08, 0x48, 0x93,
	0xed, 0x20, 0xfd, 0x0a, 0x4c, 0x91, 0x08, 0x72, 0x00, 0x8d, 0x84, 0xbb, 0x31, 0xc7, 0xfb, 0x63,
	0x50, 0x39, 0x21, 0x16, 0x18, 0x2c, 0x90, 0x57, 0xc6, 0xa0, 0x62, 0x48, 0xee, 0x41, 0x07, 0x55,
	0x67, 0x57, 0x6e, 0x8c, 0xc8, 0x6a, 0xd0, 0x5c, 0x40, 0x6c, 0x68, 0xb1, 0x60, 0x8e, 0x3a, 0x13,
	0x75, 0xe9, 0xd4, 0xf9, 0x1d, 0xd8, 0xdb, 0x10, 0xaf, 0x84, 0xb9, 0xda, 0x87, 0x61, 0xee, 0x21,
	0xf4, 0x11, 0xb6, 0x68, 0xf8, 0x76, 0x12, 0xcc, 0xd9, 0x35, 0x6e, 0xb5, 0x41, 0xcb, 0x42, 0xe7,
	0xcf, 0x7a, 0x4a, 0x45, 0x44, 0x6b, 0xb8, 0x0f, 0xe0, 0x7a, 0x7c, 0xed, 0x2e, 0x67, 0xec, 0x9a,
	0x2b, 0xbc, 0x28, 0x48, 0x84, 0x3e, 0x72, 0xe3, 0x84, 0xcd, 0x51, 0xaf, 0x4b, 0x7d, 0x2e, 0x21,
	0x4f, 0xa0, 0xf3, 0x2a, 0x76, 0x17, 0x02, 0xdd, 0x52, 0xbc, 0xb0, 0xab, 0xfb, 0x3d, 0x57, 0x06,
	0x34, 0x37, 0x15, 0xfd, 0x41, 0xb4, 0xa6, 0xac, 0x84, 0x28, 0x4b, 0xd6, 0x4b, 0xae, 0xba, 0xcc,
	0xd1, 0xd6, 0x86, 0x56, 0xb1, 0xa7, 0x75, 0x8b, 0xd4, 0x95, 0x5d, 0x63, 0xf7, 0xb2, 0x6b, 0xd6,
	0x97, 0x9d, 0xf3, 0x4f, 0x0d, 0x7a, 0xc5, 0x36, 0x49, 0x7e, 0x0a, 0x5d, 0xd5, 0x28, 0xc5, 0xce,
	0xd4, 0x61, 0xbd, 0xa7, 0x17, 0x17, 0xad, 0x05, 0xc1, 0x4b, 0xf0, 0x22, 0xdf, 0x4c, 0xf0, 0xd0,
	0x8e, 0xfc, 0x06, 0xee, 0x28, 0xff, 0x6a, 0xce, 0x8c, 0x0f, 0xcc, 0xd9, 0x96, 0x75, 0x9c, 0x07,
	0xaa, 0x2e, 0x44, 0x83, 0xc9, 0x80, 0x4f, 0xcb, 0x81, 0xcf, 0x79, 0xa7, 0x41, 0x3b, 0x3d, 0x4b,
	0x32, 0x81, 0x5e, 0x7a, 0x9a, 0x05, 0x1a, 0xf3, 0xd1, 0xb6, 0xb3, 0xcf, 0x06, 0xc8, 0x64, 0x4a,
	0xae, 0xf8, 0xad, 0xbc, 0xba, 0x70, 0x4c, 0x3e, 0x83, 0x4e, 0xe4, 0xc6, 0xee, 0x8a, 0x71, 0x16,
	0xab, 0x08, 0x37, 0x73, 0x94, 0x1a, 0xd0, 0xdc, 0xd6, 0xf9, 0x18, 0x7a, 0xc5, 0x4f, 0x61, 0xc7,
	0x64, 0xd7, 0xdc, 0xda, 0x23, 0x7d, 0xe8, 0x64, 0x1e, 0x96, 0xe6, 0xfc, 0x41, 0x2f, 0xcc, 0xc9,
	0x97, 0xd0, 0xcf, 0xd6, 0x28, 0xc4, 0xf3, 0xf1, 0xd6, 0x6f, 0xe6, 0x23, 0x8c, 0xa8, 0xec, 0x2d,
	0x10, 0xe4, 0x8d, 0xbb, 0x5c, 0x33, 0x15, 0x93, 0x9c, 0x88, 0x40, 0x03, 0x41, 0x70, 0x0d, 0x19,
	0xa8, 0x18, 0xe7, 0xa4, 0xc4, 0xdc, 0x91, 0x94, 0x38, 0x5f, 0x41, 0xbf, 0xf4, 0x6d, 0x02, 0xd0,
	0x14, 0x80, 0xeb, 0x7b, 0x92, 0x6c, 0x8c, 0xbe, 0x0d, 0xdc, 0x95, 0xef, 0x59, 0x1a, 0x21, 0x30,
	0x10, 0xef, 0x0d, 0xdf, 0x5d, 0x7e, 0x3d, 0xe5, 0xb1, 0x1f, 0x2c, 0x2c, 0x9d, 0xdc, 0x82, 0x7e,
	0x2a, 0x93, 0xa4, 0xc2, 0xc8, 0xf9, 0x85, 0xe9, 0x38, 0x59, 0x8d, 0x4b, 0xca, 0x94, 0x1e, 0x8d,
	0x96, 0x1f, 0x8d, 0x73, 0x0d, 0x90, 0x6f, 0x8a, 0x7c, 0x06, 0xad, 0x2b, 0xe6, 0xce, 0x59, 0x9c,
	0xbc, 0x17, 0xae, 0x66, 0x0a, 0x83, 0x68, 0x6a, 0x4d, 0x7e, 0x04, 0x66, 0x1c, 0xbe, 0x4d, 0x2f,
	0xc0, 0x0d, 0x5e, 0x68, 0xea, 0x7c, 0xa4, 0x28, 0x4f, 0x2a, 0x16, 0x69, 0xf6, 0xd8, 0x72, 0x99,
	0x96, 0xa9, 0x9c, 0x38, 0x7f, 0xd1, 0x15, 0xbe, 0xd6, 0x54, 0x3f, 0xb9, 0x28, 0xb4, 0x37, 0x75,
	0x81, 0xe4, 0xbe, 0x0f, 0x6b, 0x77, 0x50, 0xbd, 0x3c, 0x55, 0xe7, 0x1a, 0xde, 0xa2, 0xff, 0xef,
	0x78, 0x8b, 0xf1, 0xdf, 0xf2, 0x16, 0x3b, 0x67, 0x1f, 0x26, 0x3e, 0x04, 0x33, 0xe6, 0x71, 0x08,
	0x7d, 0x35, 0xa4, 0xcc, 0x4d, 0xc2, 0x00, 0x69, 0x56, 0x87, 0x96, 0x85, 0xce, 0xbf, 0x74, 0x38,
	0xa8, 0x8b, 0x9f, 0xdc, 0xc9, 0xa8, 0xa3, 0x86, 0xeb, 0xa6, 0xb4, 0xf1, 0x21, 0x58, 0x31, 0xf3,
	0xc2, 0x37, 0x2c, 0x16, 0x67, 0x83, 0x2c, 0x46, 0x92, 0x4b, 0xba, 0x21, 0x27, 0x0e, 0xf4, 0x98,
	0x18, 0xa4, 0x1d, 0x59, 0x5e, 0x87, 0x92, 0x0c, 0x09, 0x12, 0x77, 0xbd, 0xd7, 0xb3, 0xd8, 0xf5,
	0xe4, 0xdd, 0x10, 0x04, 0x29, 0x93, 0xa0, 0xde, 0x8b, 0x19, 0x0b, 0xa6, 0x57, 0x21, 0xc7, 0x18,
	0x7a, 0xb4, 0x20, 0xd9, 0x24, 0x69, 0xcd, 0x3a, 0x92, 0x66, 0x43, 0x4b, 0x25, 0x55, 0x31, 0xbc,
	0x74, 0x4a, 0x9e, 0x41, 0x07, 0xf7, 0x83, 0x58, 0xd0, 0x46, 0x2c, 0x38, 0xde, 0xa5, 0x40, 0x8e,
	0xc7, 0xa9, 0x17, 0xcd, 0x17, 0x70, 0x1e, 0x41, 0x27, 0x93, 0x0b, 0x1c, 0x3a, 0x9d, 0x4e, 0xc7,
	0x74, 0x36, 0x79, 0x7e, 0x61, 0xed, 0x11, 0x0b, 0x7a, 0x2f, 0xc6, 0x74, 0x72, 0x3e, 0x39, 0x3b,
	0x45, 0x89, 0xe6, 0xfc, 0x51, 0x03, 0xab, 0x7a, 0xc4, 0x95, 0x84, 0x68, 0x1b, 0x09, 0xa9, 0x26,
	0x55, 0xdf, 0x92, 0xd4, 0x3c, 0x69, 0x46, 0x5d, 0xd2, 0xca, 0x04, 0xc2, 0xac, 0x23, 0x10, 0xef,
	0x1a, 0x6a, 0x7b, 0xd3, 0xb5, 0xcf, 0x99, 0xaa, 0x8b, 0x53, 0xf9, 0x4b, 0x43, 0xce, 0xe4, 0x7d,
	0xec, 0x6e, 0x32, 0xc6, 0xec, 0x17, 0x88, 0xba, 0x4d, 0x45, 0x9f, 0xff, 0xd3, 0x9b, 0x94, 0x17,
	0xbc, 0x59, 0x2d, 0x78, 0xb1, 0xf9, 0xe4, 0x1c, 0xa7, 0x67, 0xe1, 0x3a, 0x90, 0x65, 0xd8, 0xa0,
	0x1b, 0xf2, 0x1d, 0x8b, 0x71, 0x08, 0xdd, 0x64, 0xed, 0x79, 0x2c, 0x49, 0xa8, 0xcb, 0xe5, 0x23,
	0x55, 0xa7, 0x45, 0x91, 0xb0, 0x60, 0xc1, 0x1b, 0x3f, 0x0e, 0x03, 0x7c, 0xfc, 0xb6, 0xe5, 0x7f,
	0xa3, 0x82, 0x28, 0x6b, 0xdb, 0x1d, 0x85, 0xd7, 0xa2, 0x95, 0x0f, 0xa1, 0x1b, 0xc5, 0xe1, 0x37,
	0xcc, 0xe3, 0xf8, 0x77, 0x05, 0xa4, 0x57, 0x41, 0x24, 0x78, 0x2c, 0xf7, 0x57, 0x2c, 0xe1, 0xee,
	0x2a, 0x52, 0x8f, 0x8e, 0x5c, 0x40, 0x1e, 0xc1, 0x2d, 0x8c, 0x68, 0x2a, 0x11, 0x42, 0x86, 0xda,
	0xc3, 0x50, 0x37, 0x15, 0x75, 0xe4, 0xab, 0xbf, 0x3b, 0xf9, 0x1a, 0xec, 0xcc, 0xf9, 0xf7, 0x3f,
	0x84, 0xf3, 0x5b, 0xdb, 0x39, 0xff, 0x5f, 0x0d, 0xd8, 0xaf, 0x94, 0x25, 0x92, 0x8f, 0x54, 0xf4,
	0x7e, 0x5e, 0x27, 0x7c, 0x72, 0x5b, 0x04, 0x57, 0xc5, 0xc6, 0x65, 0x9a, 0x14, 0x03, 0x2f, 0x09,
	0xc9, 0x63, 0xb8, 0x9d, 0x0a, 0x8a, 0xd5, 0x63, 0xa0, 0x6d, 0x9d, 0x6a, 0x6b, 0x11, 0x3e, 0x86,
	0xdb, 0x72, 0x34, 0x72, 0xb9, 0x9b, 0x76, 0x45, 0xc9, 0x76, 0x1b, 0xb4, 0x4e, 0xb5, 0x3b, 0x2e,
	0xa6, 0xed, 0xa3, 0x55, 0x6e, 0x1f, 0x27, 0x70, 0x90, 0x6e, 0xb0, 0x54, 0x0f, 0x6d, 0xdc, 0x7c,
	0xad, 0x0e, 0x7d, 0xe4, 0xbc, 0xbc, 0xcd, 0x0e, 0x6e, 0xb3, 0x56, 0x47, 0x3e, 0x81, 0x26, 0xcb,
	0x1f, 0xc7, 0xdd, 0x93, 0xef, 0x6c, 0x3c, 0x3e, 0x85, 0x96, 0x2a, 0x23, 0xe7, 0x6f, 0x1a, 0x34,
	0x64, 0x73, 0xf9, 0x14, 0x4c, 0x9e, 0xf3, 0xb7, 0x07, 0xb5, 0x6e, 0x05, 0x90, 0x46, 0xe3, 0xf4,
	0xef, 0x23, 0x92, 0x33, 0x3d, 0xff, 0xfb, 0x88, 0x04, 0xed, 0x3e, 0xc0, 0xd2, 0x0f, 0xd8, 0xc5,
	0x7a, 0xf5, 0x52, 0x51, 0xd1, 0x06, 0x2d, 0x48, 0x8a, 0x3d, 0x44, 0xb6, 0xa9, 0x74, 0xea, 0x9c,
	0x14, 0x51, 0x7f, 0x1f, 0xba, 0x97, 0xa7, 0x74, 0x3a, 0xfe, 0x7a, 0x4c, 0xe9, 0x73, 0x6a, 0xed,
	0x91, 0x03, 0xb0, 0x5e, 0x9c, 0x3e, 0x9b, 0x8c, 0x10, 0xf5, 0x95, 0x54, 0x73, 0x7e, 0xaf, 0xc1,
	0x20, 0xe3, 0x2e, 0x2f, 0x90, 0x35, 0xe2, 0x2b, 0x53, 0x4d, 0x14, 0xf0, 0xe7, 0x02, 0xf2, 0x04,
	0xee, 0x64, 0xd4, 0xd3, 0xff, 0x2d, 0x9b, 0x67, 0x7e, 0x2a, 0x90, 0x2d, 0x5a, 0xf5, 0xb0, 0x93,
	0x1a, 0xf9, 0x72, 0x93, 0x0f, 0x3b, 0x25, 0x79, 0xf8, 0x05, 0xec, 0x57, 0xde, 0xf7, 0x22, 0x84,
	0x8b, 0xe7, 0xb3, 0xf1, 0xaf, 0xc7, 0x67, 0xbf, 0x9a, 0x8d, 0x47, 0xd6, 0x9e, 0x20, 0x9e, 0x97,
	0xa2, 0x95, 0x8d, 0x2c, 0x4d, 0x8c, 0xcf, 0x4f, 0x27, 0xcf, 0xc6, 0x23, 0x4b, 0x17, 0x24, 0x74,
	0xfa, 0xcb, 0xc9, 0xe5, 0xe5, 0x78, 0x64, 0x19, 0x9f, 0xff, 0x40, 0x3c, 0x5c, 0x56, 0xc7, 0xfc,
	0x2a, 0x5c, 0x2f, 0xae, 0xf8, 0xdb, 0x30, 0x7e, 0x9d, 0xc8, 0x43, 0xf9, 0x93, 0x3e, 0xf8, 0x02,
	0x0f, 0x27, 0xbd, 0xe5, 0x2f, 0x9b, 0x78, 0x93, 0x3e, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc5, 0x3a, 0x3b, 0x74, 0x4a, 0x17, 0x00, 0x00,
}
