name: tests
on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v1

      - name: Setup go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: Run tests
        run: |
          go test ./...

      - name: Build and Install
        run: |
          go run build/make.go
          go run build/make.go --install
